apiVersion: v1
kind: Service
metadata:
  name: mtls-server-service
  namespace: proxy
spec:
  selector:
    app.kubernetes.io/name: mtls-server
  ports:
  - name: "grpc"
    port: 8888
    targetPort: 8888
    protocol: "TCP"
      